server:
  port: 10010 # 端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: http://192.168.204.133:8849
#      server-addr: nacos8849:8849
      discovery:
        cluster-name: HZ  # 划分集群
        namespace: d31175f7-125a-49d0-bf5c-c7e74e547eaf # dev环境
        ephemeral: false # 是否是临时实例
    gateway:
      routes:
        - id: user-service # 路由id
          uri: lb://userservice # 路由地址, lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由,只要以/user/开头就符合要求
#          filters:
#            - StripPrefix=1 # 过滤器，去掉第一个路径
        - id: order-service # 路由id
          uri: lb://orderservice # 路由地址, lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/order/** # 断言，路径相匹配的进行路由,只要以/user/开头就符合要求
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期