server:
  #  项目端口号
  port: 8080
spring:
  datasource:
    # 数据库动态配置
    dynamic:
      primary: fraud # 配置默认数据库
      datasource:
        fraud:
          driver-class-name: com.mysql.cj.jdbc.Driver
          password:
          url:
          username:

        ice:
          driver-class-name: com.mysql.cj.jdbc.Driver
          password:
          url:
          username:

  redis:
    database: 0
    cluster:
      max-redirects: 10
      nodes:
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

  galleryFactor:
    cluster:
      max-redirects: 10
      nodes:


